### ISSUE TITLE
React Router V7 + React 19 support

### ISSUE THREAD

**Issue by mdklause** [abereghici/remix-themes#47]
### Describe the bug

Remix v3 is React Router V7 in Framework Mode, which supports React 18 & 19. React Router V7 is currently not supported
#46 

### Your Example Website or App

-

### Steps to Reproduce the Bug or Issue

Installation is not possible in a new react router v7 project with react 19

### Expected behavior

I would expect the library to work in a Remix V2 App without having to use dependancy workarounds

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]

### Additional context

#

**Comment by abereghici** [comment]
Thanks for opening the issue! I'll work on it soon.

**Comment by Moonnz** [comment]
Hello !
I've made the adaptation for react-router v7 in this PR: #48

**Comment by VIEWVIEWVIEW** [comment]
> Hello ! I've made the adaptation for react-router v7 in this PR: #48

Any chance to merge? :)

**Comment by Briscoooe** [comment]
Let me know if I can help with this 🙏

**Comment by abereghici** [comment]
Thanks for the PR @Moonnz ! I'm afraid these changes will break the `remix-themes-app` and the e2e tests won't work. The app should be upgraded and tested before merging these changes. I need help with that.

**Comment by NareshBisht** [comment]
> Hello ! I've made the adaptation for react-router v7 in this PR: #48

Is the setup process same for react-router-v7?

**Comment by NareshBisht** [comment]
> Thanks for the PR @Moonnz ! I'm afraid these changes will break the `remix-themes-app` and the e2e tests won't work. The app should be upgraded and tested before merging these changes. I need help with that.

Hello @abereghici, if possible, could you provide a rough estimate of when you might be able to implement this feature? This will help us determine how to proceed. Thank you!

**Comment by abereghici** [comment]
> > Thanks for the PR @Moonnz ! I'm afraid these changes will break the `remix-themes-app` and the e2e tests won't work. The app should be upgraded and tested before merging these changes. I need help with that.
> 
> 
> 
> Hello @abereghici, if possible, could you provide a rough estimate of when you might be able to implement this feature? This will help us determine how to proceed. Thank you!

Hi! I think I will be able to do a release next week, I am still on holiday :)

**Comment by Moonnz** [comment]
Anyway @abereghici, I've push a completly new react-router app and the tests work on chrome.
I can't test firefox and webkit on my computer actually :/

**Comment by abereghici** [comment]
Thanks @Moonnz for this pull request! I noticed the unit tests are not working and I decided to refactor this package from scratch using the latest dependency versions. I created a new MR based on yours here : https://github.com/abereghici/remix-themes/pull/49

Open for any feedback!

**Comment by abereghici** [comment]
v2.0.1 released with react router support

**Comment by aimz-yeah** [comment]
This release provided support for React 19 but also **mandated** a minimum version of React 19. This breaks apps running on still React 18.x. RR7 itself supports 18.2. 

Is there a hard requirement for v19 in this release or can the requirements be loosened?

**Comment by abereghici** [comment]
@aimz-yeah I removed the requirement, v2.0.3 can be used. Sorry for the inconvenience.

**Comment by pthieu** [comment]
@abereghici what's the remix version needed for this?
I'm on:
- remix@2.15.2
- react@19.0.0
- remix-themes@2.0.4

I have this issue:
```
TypeError: Response.json is not a function
    at action (file:///Users/pthieu/www/p-stack/node_modules/.pnpm/remix-themes@2.0.4/node_modules/remix-themes/dist/index.js:260:21)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.callRouteAction (/Users/pthieu/www/p-stack/node_modules/.pnpm/@remix-run+server-runtime@2.15.2_typescript@5.7.3/node_modules/@remix-run/server-runtime/dist/data.js:36:16)
    at /Users/pthieu/www/p-stack/node_modules/.pnpm/@remix-run+router@1.21.0/node_modules/@remix-run/router/router.ts:4899:19
```

**Comment by Mariuble** [comment]
> [@abereghici](https://github.com/abereghici) what's the remix version needed for this? I'm on:
> 
> * remix@2.15.2
> * react@19.0.0
> * remix-themes@2.0.4 


If you are using Remix.run you can use v1.6.1 of this library or lower, v2 onwards is only react-router v7 compatible.
